import Head from "next/head";
import { Inter } from "next/font/google";
import Nav from "../components/nav/nav"
import Card from "../components/card/card"

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const data = {
    pokemons: [
      {
        name: "Bulbasaur",
        image: "https://img.pokemondb.net/artwork/bulbasaur.jpg",
      },
      {
        name: "Ivysaur",
        image: "https://img.pokemondb.net/artwork/ivysaur.jpg",
      },
      {
        name: "Venusaur",
        image: "https://img.pokemondb.net/artwork/venusaur.jpg",
      },
      {
        name: "Charmander",
        image: "https://img.pokemondb.net/artwork/charmander.jpg",
      },
      {
        name: "Charmeleon",
        image: "https://img.pokemondb.net/artwork/charmeleon.jpg",
      },
      {
        name: "Charizard",
        image: "https://img.pokemondb.net/artwork/charizard.jpg",
      },
      {
        name: "Squirtle",
        image: "https://img.pokemondb.net/artwork/squirtle.jpg",
      },
      {
        name: "Wartortle",
        image: "https://img.pokemondb.net/artwork/wartortle.jpg",
      },
      {
        name: "Blastoise",
        image: "https://img.pokemondb.net/artwork/blastoise.jpg",
      },
      {
        name: "Caterpie",
        image: "https://img.pokemondb.net/artwork/caterpie.jpg",
      },
    ],
  };

  return (
    <>
      <Head>
        <title>Home | Pokedex Arsy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="grid grid-cols-[repeat(auto-fill,minmax(min(320px,100%),1fr))] gap-12 p-12">
        {data.pokemons.map((el) => (
          <Card name={el.name} image={el.image} key={el.name} />
        ))}
      </main>
    </>
  );
}
