import Head from "next/head";
import { Inter } from "next/font/google";
import Nav from "../components/nav/nav";
import Card from "../components/card/card";
import client from "../../apollo-client";
import { gql } from "@apollo/client";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ pokemons }) {
  return (
    <>
      <Head>
        <title>Home | Pokedex Arsy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="grid grid-cols-[repeat(auto-fill,minmax(min(320px,100%),1fr))] gap-12 p-12">
        {pokemons.map((el) => (
          <Card name={el.name} image={el.image} key={el.name} />
        ))}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      query Pokemons {
        pokemons(first: 5) {
          name
          image
        }
      }
    `,
  });

  return {
    props: {
      pokemons: data.pokemons,
    }
  }
}
